topic 0
faltamiranda/startup pull request #1
Opened 2016-10-04 20:37 UTC by faltamiranda

2016-10-04 21:55 UTC, afiorenza requested changes

2016-10-04 21:55 UTC, afiorenza commented on 00-HTML-CSS-basics/trabajos/css/2.1.4/index.html
> +<div class="header">
Check indentation

2016-10-04 21:55 UTC, afiorenza commented on 00-HTML-CSS-basics/trabajos/css/2.1.4/index.html
> +
Avoid the use of breaklines

2016-10-04 21:55 UTC, afiorenza commented on 00-HTML-CSS-basics/trabajos/html/trabajo4.html
> +    First name: <input type="text" name="fname" id="fname" value=""  required="" /><br>
Try to use labels

2016-10-05 19:59 UTC, faltamiranda commented on 00-HTML-CSS-basics/trabajos/css/2.1.4/index.html
> +<div class="header">
done

2016-10-05 19:59 UTC, faltamiranda commented on 00-HTML-CSS-basics/trabajos/css/2.1.4/index.html
> +
done

2016-10-05 19:59 UTC, faltamiranda commented on 00-HTML-CSS-basics/trabajos/html/trabajo4.html
> +    First name: <input type="text" name="fname" id="fname" value=""  required="" /><br>
done

2016-10-06 01:55 UTC, afiorenza approved these changes

2016-10-06 17:12 UTC, merged